language: python

python:
  - "3.7"
  - "3.8"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

before_install:
  - pip install pip codecov --upgrade

install:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make test
  - codecov

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
    email: false
