language: python

python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"

before_install:
  - pip install pip --upgrade

install:
  - make install

script:
  - make test
  - codecov

notifications:
    email: false
